// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class FirebaseConfig {
  /// Billing açıldığında true yapılacak
  static const bool enabled = false;
}


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNkcnear3wNjj8mmbgj8F4WJ_59aVmC10',
    appId: '1:742414660610:web:2b425c39b6419a4d8fa31b',
    messagingSenderId: '742414660610',
    projectId: 'my-digidrobe',
    authDomain: 'my-digidrobe.firebaseapp.com',
    storageBucket: 'my-digidrobe.firebasestorage.app',
    measurementId: 'G-10L81D8SFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGbetAvCjiYBoQMcStZ7GHW0BLn_7nEE',
    appId: '1:742414660610:android:17d29915c8bf34078fa31b',
    messagingSenderId: '742414660610',
    projectId: 'my-digidrobe',
    storageBucket: 'my-digidrobe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHiUF3mTpC9w737BYdUf2ydiGeHjdhzFk',
    appId: '1:742414660610:ios:3e5c31f73f14cdde8fa31b',
    messagingSenderId: '742414660610',
    projectId: 'my-digidrobe',
    storageBucket: 'my-digidrobe.firebasestorage.app',
    iosBundleId: 'com.example.myDigidrobe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHiUF3mTpC9w737BYdUf2ydiGeHjdhzFk',
    appId: '1:742414660610:ios:3e5c31f73f14cdde8fa31b',
    messagingSenderId: '742414660610',
    projectId: 'my-digidrobe',
    storageBucket: 'my-digidrobe.firebasestorage.app',
    iosBundleId: 'com.example.myDigidrobe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNkcnear3wNjj8mmbgj8F4WJ_59aVmC10',
    appId: '1:742414660610:web:468fb5b57699e3e38fa31b',
    messagingSenderId: '742414660610',
    projectId: 'my-digidrobe',
    authDomain: 'my-digidrobe.firebaseapp.com',
    storageBucket: 'my-digidrobe.firebasestorage.app',
    measurementId: 'G-N5R0DTMH5X',
  );
}
